# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XUFJ0wClFYb2ZTCp8BzD0Gq10OffDkAP

### 프로그램 흐름
1. 문장 입력 (임시로 input()처리 해뒀지만 추후 프론트에서 전달받은 문장으로 진행)
2. 토큰화 및 모델 돌리기 -> 결과물로 감정 단어 리스트 출력
4. 감정 단어 분석하여 감정 도출 -> 데이터베이스에 저장
5. 이후 모듈은 무조건 데이터베이스에 접근하여 구현


!pip install transformers
!pip install torch

from transformers import ElectraTokenizer, ElectraForSequenceClassification
import torch

# 토크나이저와 모델 불러오기 (감정 분석용 fine-tuned 모델 사용 가능)
tokenizer = ElectraTokenizer.from_pretrained("monologg/koelectra-base-v3-discriminator")
model = ElectraForSequenceClassification.from_pretrained("monologg/koelectra-base-v3-discriminator")

EMOTIONS_LIST = ("행복/만족", "우울/피곤", "불안/걱정", "분노/짜증", "설렘/흥분", "외로움/공허", "평온/안정") # 원래 constants.py를 임포트해야하는데 임시로 여기 넣어요

sentence = input()
inputs = tokenizer(sentence, return_tensors="pt")

outputs = model(**inputs)
logits = outputs.logits
predicted_class = torch.argmax(logits).item()

print("예측된 클래스:", predicted_class)

# 방법 1: 토큰 별 감정 점수 계산
tokens = tokenizer.tokenize(sentence)
inputs = tokenizer(sentence, return_tensors="pt")

with torch.no_grad():
    outputs = model(**inputs)

# logits에서 가장 강한 감정 클래스 확인
logits = outputs.logits
predicted_class = torch.argmax(logits, dim=-1).item()

print("문장 전체 감정:", predicted_class)
print("토큰들:", tokens)

# 방법 2: 사전 기반 감정 단어 필터링
emotion_words = ["행복", "기분", "좋아", "슬프다", "화나다", "즐겁다"]
extracted = [tok for tok in tokens if tok in emotion_words]
print("감정 단어 추출:", extracted)
"""