# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XUFJ0wClFYb2ZTCp8BzD0Gq10OffDkAP

### 프로그램 흐름
1. 문장 입력 (임시로 input()처리 해뒀지만 추후 프론트에서 전달받은 문장으로 진행)
2. 토큰화 및 모델 돌리기 -> 결과물로 감정 단어 리스트 출력
4. 감정 단어 분석하여 감정 도출 -> 데이터베이스에 저장
5. 이후 모듈은 무조건 데이터베이스에 접근하여 구현

### 프로그램 구조 예시
project/
├── frontend.py  <- 프론트 (파일 더 있어도 상관없어요!)  
├── tokenizer_model.py  <- 토크나이저와 모델 & 감정 단어 분석해서 최종 감정 도출  
├── emotion_db.py  <- 데이터베이스 구현용 모듈  
├── graphs.py  <- 그래프 만들거나 그런 거 하는 모듈  
└── data/  
    └── emotions.json  <- 데이터베이스  
    └── CONSTANTS.json  <- 뭐라고 해야 할 지 몰라서 일단 상수라고 했는데 감정문장이나 그런 불변하는 데이터 저장하는 DB입니다
"""

!pip install transformers
!pip install torch

from transformers import ElectraTokenizer, ElectraForSequenceClassification
import torch

# 토크나이저와 모델 불러오기 (감정 분석용 fine-tuned 모델 사용 가능)
tokenizer = ElectraTokenizer.from_pretrained("monologg/koelectra-base-v3-discriminator")
model = ElectraForSequenceClassification.from_pretrained("monologg/koelectra-base-v3-discriminator")

EMOTIONS_LIST = ("행복/만족", "우울/피곤", "불안/걱정", "분노/짜증", "설렘/흥분", "외로움/공허", "평온/안정") # 원래 constants.py를 임포트해야하는데 임시로 여기 넣어요

sentence = input()
inputs = tokenizer(sentence, return_tensors="pt")

outputs = model(**inputs)
logits = outputs.logits
predicted_class = torch.argmax(logits).item()

print("예측된 클래스:", predicted_class)

# 방법 1: 토큰 별 감정 점수 계산
tokens = tokenizer.tokenize(sentence)
inputs = tokenizer(sentence, return_tensors="pt")

with torch.no_grad():
    outputs = model(**inputs)

# logits에서 가장 강한 감정 클래스 확인
logits = outputs.logits
predicted_class = torch.argmax(logits, dim=-1).item()

print("문장 전체 감정:", predicted_class)
print("토큰들:", tokens)

# 방법 2: 사전 기반 감정 단어 필터링
emotion_words = ["행복", "기분", "좋아", "슬프다", "화나다", "즐겁다"]
extracted = [tok for tok in tokens if tok in emotion_words]
print("감정 단어 추출:", extracted)

"""데이터베이스"""

# emotions_db.py

import json
from datetime import datetime
from pathlib import Path

DB_PATH = Path("data/emotions.json")

def init_db():
    if not DB_PATH.exists():
        with open(DB_PATH, "w", encoding="utf-8") as f:
            json.dump([], f)

def add_emotion(emotion: str):
    with open(DB_PATH, "r+", encoding="utf-8") as f:
        data = json.load(f)
        new_entry = {
            "id": len(data) + 1,
            "date": datetime.now().strftime("%Y-%m-%d"),
            "emotion": emotion
        }
        data.append(new_entry)
        f.seek(0)
        json.dump(data, f, indent=4, ensure_ascii=False)

def get_all_emotions():
    with open(DB_PATH, "r", encoding="utf-8") as f:
        return json.load(f)

"""데이터베이스 형태 예시 (구현하실 때 일단 이거 가져다가 쓰시면 될 것 같아요)"""

# emotions.json

[
  {
    "id": 1,
    "date": "2026-06-06",
    "emotion": "행복/만족"
  },
  {
    "id": 2,
    "date": "2026-06-07",
    "emotion": "우울/피곤"
  },
  {
    "id": 3,
    "date": "2026-06-08",
    "emotion": "불안/걱정"
  },
  {
    "id": 4,
    "date": "2026-06-09",
    "emotion": "행복/만족"
  },
]

# CONSTANTS.py

EMOTIONS_LIST = ("행복/만족", "우울/피곤", "불안/걱정", "분노/짜증", "설렘/흥분", "외로움/공허", "평온/안정")

RELATING_WORDS_LIST = {     #임시로 짠 거라 구조 이상하면 바꿀 수도 있어요
    "행복/만족":{"예시문장1", "예시문장2"},
    "우울/피곤":{},
    "불안/걱정":{},
    "분노/짜증":{},
    "설렘/흥분":{},
    "외로움/공허":{},
    "평온/안정":{}
}